/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductRecognitionRouteImport } from './routes/_authenticated/product-recognition'
import { Route as AuthenticatedProductComparisonRouteImport } from './routes/_authenticated/product-comparison'
import { Route as AuthenticatedFakeDetectorRouteImport } from './routes/_authenticated/fake-detector'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiDetectionRouteImport } from './routes/_authenticated/ai-detection'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductRecognitionRoute =
  AuthenticatedProductRecognitionRouteImport.update({
    id: '/product-recognition',
    path: '/product-recognition',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductComparisonRoute =
  AuthenticatedProductComparisonRouteImport.update({
    id: '/product-comparison',
    path: '/product-comparison',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFakeDetectorRoute =
  AuthenticatedFakeDetectorRouteImport.update({
    id: '/fake-detector',
    path: '/fake-detector',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiDetectionRoute =
  AuthenticatedAiDetectionRouteImport.update({
    id: '/ai-detection',
    path: '/ai-detection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fake-detector': typeof AuthenticatedFakeDetectorRoute
  '/product-comparison': typeof AuthenticatedProductComparisonRoute
  '/product-recognition': typeof AuthenticatedProductRecognitionRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fake-detector': typeof AuthenticatedFakeDetectorRoute
  '/product-comparison': typeof AuthenticatedProductComparisonRoute
  '/product-recognition': typeof AuthenticatedProductRecognitionRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fake-detector': typeof AuthenticatedFakeDetectorRoute
  '/_authenticated/product-comparison': typeof AuthenticatedProductComparisonRoute
  '/_authenticated/product-recognition': typeof AuthenticatedProductRecognitionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-detection'
    | '/dashboard'
    | '/fake-detector'
    | '/product-comparison'
    | '/product-recognition'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-detection'
    | '/dashboard'
    | '/fake-detector'
    | '/product-comparison'
    | '/product-recognition'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-detection'
    | '/_authenticated/dashboard'
    | '/_authenticated/fake-detector'
    | '/_authenticated/product-comparison'
    | '/_authenticated/product-recognition'
    | '/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-recognition': {
      id: '/_authenticated/product-recognition'
      path: '/product-recognition'
      fullPath: '/product-recognition'
      preLoaderRoute: typeof AuthenticatedProductRecognitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-comparison': {
      id: '/_authenticated/product-comparison'
      path: '/product-comparison'
      fullPath: '/product-comparison'
      preLoaderRoute: typeof AuthenticatedProductComparisonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fake-detector': {
      id: '/_authenticated/fake-detector'
      path: '/fake-detector'
      fullPath: '/fake-detector'
      preLoaderRoute: typeof AuthenticatedFakeDetectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-detection': {
      id: '/_authenticated/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AuthenticatedAiDetectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiDetectionRoute: typeof AuthenticatedAiDetectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFakeDetectorRoute: typeof AuthenticatedFakeDetectorRoute
  AuthenticatedProductComparisonRoute: typeof AuthenticatedProductComparisonRoute
  AuthenticatedProductRecognitionRoute: typeof AuthenticatedProductRecognitionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiDetectionRoute: AuthenticatedAiDetectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFakeDetectorRoute: AuthenticatedFakeDetectorRoute,
  AuthenticatedProductComparisonRoute: AuthenticatedProductComparisonRoute,
  AuthenticatedProductRecognitionRoute: AuthenticatedProductRecognitionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
